version: '3.8'

services:
  ocr_api:
    build: .
    
    ports:
      - "8000:8000"
    
    restart: always

    environment:
      - TYPHOON_API_KEY=${TYPHOON_API_KEY}
    
    networks:
      - ocr_net

networks:
  ocr_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.10.0/24